[build]
  publish = "public"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/weather"
  to = "/.netlify/functions/weather"
  status = 200

[functions]
  directory = "netlify/functions"
